### PR TITLE
Part #274, Cleanup and add doxygen for cfe_psp.h

### LINKED ISSUE #274: PSP Headers need a scrub/cleanup
**Is your feature request related to a problem? Please describe.**
The `cfe_psp.h` header file puts its comments/description _after_ the function declaration and does not use doxygen style.  It also contains at least a few functions that are not used by CFE and also may not even be implemented

**Describe the solution you'd like**
Cleanup.   At least fixup comments to be more readable - put before declaration and ideally also add some doxygen markup. 

At least the `CFE_PSP_Decompress()` function appears to be not implemented at all - recommend removing this prototype.

**Additional context**
Other functions which are inconsistently implemented or too hardware specific to be useful, might be targets for deprecation/removal (These are not used by CFE, either):

-[] `CFE_PSP_InitSSR()` - why an init but no read/write/mount/etc?  Seems like a thought that was never completed.
-[] `CFE_PSP_Get_Timer_Tick()` - note this is different than `CFE_PSP_GetTimerTicksPerSecond()`
-[] `CFE_PSP_Get_Dec()` - not well defined what this value really is, so not really usable in portable apps.

These are referenced but have some issues:
-[] `CFE_PSP_GetTime()` - The definition is inconsistent, sometimes it maps to a real clock and sometimes its more of an interval timer with an arbitrary wrap point, needs more info/definition at least because it is generally hard to use __correctly__.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Part: #274 

I have not attempted to split up the header, nor removed any functions - I intended to leave those as separate work items in the original issue or open a new issue for them. Can also remove functions in this PR if there is consensus/advice to do so.

Doxygen markup added, along with more detail for @param's, @return's etc.

Moved some existing function header information from the implementation files into `cfe_psp.h` - *unless* there is platform-specific information in that particular variant's function header comment. The .h file is the logical and central 'source-of-truth' for the function header information, and doubling it up (or tripling/quadrupling in the case of PSP) just leads to inconsistencies when updates occur.

Comments referring to `BSPReadCDSRtn`, `BSPWriteCDSRtn` and `PSPRestartRt` were removed as these seem to be no longer implemented - unless they exist in some other non-public implementation?

Also, is `PtrToDataToRead` a bit of a misnomer? (the pointer is for storage of the data no?)

**Testing performed**
Just GitHub CI.

**Expected behavior changes**
Documentation changes only.

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

**Comment by skliper** [comment]
Change `Fix` to `Part` in commit comment, rebase.  Great technical debt reduction!

**Comment by thnkslprpt** [comment]
> Change `Fix` to `Part` in commit comment, rebase. Great technical debt reduction!

@skliper That's all done mate

**Comment by skliper** [comment]
@thnkslprpt commit still says `fix`.  I think you can do a `git commit --amend` and change it to say `Part #274...`

**Comment by thnkslprpt** [comment]
> @thnkslprpt commit still says `Fix...`. I think you can do a `git commit --amend` and change it to say `Part #274...`

@skliper Sorry - got things backwards. Should be correct now.

**Comment by skliper** [comment]
Note I also took out the word "fixes" from the PR text so it won't link the issue for automatic closure.  Good to go!

**Review by skliper — APPROVED** [review]

**Pull request merged**
