### PR TITLE
Fix #169, make separate targets for PSP

### LINKED ISSUE #169: Build PSP components as a separate targets
**Is your feature request related to a problem? Please describe.**
As part of coverage testing that is being introduced in #168, it will require rebuilding the PSP code more than once, to make a variant that include coverage instrumentation.  This requires a bit of restructuring to support.

**Describe the solution you'd like**
Build components (e.g. shared directory) as separate targets so they can be added more than once with different configurations.
Define all target names using a separate re-definable string such as `${CFE_PSP_TARGETNAME}` rather than `${CFE_SYSTEM_PSPNAME}` to avoid target name conflicts.

**Additional context**
Prerequisite to #168, isolated to separate issue because it affects FSW headers and build scripts, not just unit test, and therefore warrants separate review.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Restructure code to make more amicable for rebuilding in a unit test environment. No major changes, primarily just shifting code between locations/headers to support unit testing.

Fixes #169 

**Testing performed**
Build and sanity check CFE on RTEMS and Linux
Run all unit tests and confirm passing.

**Expected behavior changes**
No impact to behavior.

**System(s) tested on**
Ubuntu 20.04
RTEMS 4.11.3 via QEMU/pc686

**Additional context**
Makes the code structure better for unit testing.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by astrogeco** [comment]
CCB 2020-06-17: @skliper and @jphickey will have a splinter to discuss design approach

**Comment by astrogeco** [comment]
@skliper and @jphickey what's the status on this?

**Comment by jphickey** [comment]
So far we haven't had a splinter meeting about this but I'm happy to do so any time.  The unique case here is that it is building the UT for potentially _other_ targets than what the FSW is built for (like OSAL coverage) but unlike OSAL coverage it is building it as one unit, not separate units.  So IMO this use-case made sense to use the same CMakeLists.txt subdir files create the same targets but with a different name.

Ideally in a future version I'd like to pursue the concept of a fully-modular PSP, where the PSP is just an assembly of extra modules linked into cfe core.  Then each module can get its own separate coverage test.  But in the meantime I think this works for the current PSP architecture.

**Comment by skliper** [comment]
I'm good with it, just needed to look again.  I also really like the direction of treating PSP as an assembly of extra modules.

**Comment by astrogeco** [comment]
> I'm good with it, just needed to look again. I also really like the direction of treating PSP as an assembly of extra modules.

So should I add it to IC-20200617?

**Comment by skliper** [comment]
> > I'm good with it, just needed to look again. I also really like the direction of treating PSP as an assembly of extra modules.
> 
> So should I add it to IC-20200617?

Yes please!  The sooner the better.

**Pull request merged**
