### PR TITLE
Fix #111, do not assume a specific core name

### LINKED ISSUE #111: mcp750-vxworks PSP hardcodes core as "cfe-core.o"
**Requested feature**
CFE_PSP_GetCFETextSegmentInfo fails if CFE_MODULE_NAME doesn't match what was run, currently hardcoded to "cfe-core.o".  Could make lookup more general so it wouldn't require hardcoded name.

**To Reproduce**
1. Build for vxworks, use core name other than cfe-core.o (cfe-core.exe)
2. Execute
3. Checksum of text segment will report as 0xFFFF due to failed moduleFindByName on hardcoded cfe-core.o

**Expected behavior**
Checksum should work

**Code snips**
See fsw/mcp750-vxworks/src/cfe_psp_memory.c lines related to CFE_MODULE_NAME

**System observed on:**
 - Hardware: MCP750
 - OS: VxWorks6.9
 - Versions 6.7 bundle

**Additional context**
None

**Reporter Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Improve the module ID lookup when getting the CFE core text segment info.

- Ideally get the ID directly from what was loaded by startCfeCore
- As a fallback use the actual CFE core name from the configdata

Do not use a hardcoded name.

Fixes #111 

**Testing performed**
Build and run unit tests

**Expected behavior changes**
VxWorks PSP should use the real module name, not assume `cfe-core.o` when getting text segment info

**System(s) tested on**
Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by skliper** [comment]
CCB: 2020-10-14: Approved (pending test).  Requesting ticket to add a functional test (not implemented is OK on platforms that don't support it).

**Comment by astrogeco** [comment]
@jphickey and @skliper did you all open the related ticket? Can you let me know when this is ready to merge?

**Comment by jphickey** [comment]
Yes - I was able to run this on the MCP750 and confirm that I'm getting a valid result from `CFE_PSP_GetCFETextSegmentInfo()` and subsequently CFE is calculating a checksum as expected.

@astrogeco this should be OK to merge.

**Comment by jphickey** [comment]
Note - the part I am not able to test is the one where `GetCfeCoreModuleID` is provided - because this requires rebuilding the kernel.  That can be tested at a later date.  In the meantime using the default filename seems to work fine as long as you don't rename the file from what CMake actually built.

**Comment by skliper** [comment]
> Note - the part I am not able to test is the one where `GetCfeCoreModuleID` is provided - because this requires rebuilding the kernel. That can be tested at a later date. In the meantime using the default filename seems to work fine as long as you don't rename the file from what CMake actually built.

Copy, fine by me.

**Pull request merged**
