### PR TITLE
Fix #162, reference generic OSAL BSP

### LINKED ISSUE #162: Reference the generic OSAL BSPs
**Is your feature request related to a problem? Please describe.**
Recent OSAL changes make the BSP layer more generic for VxWorks and Linux.  In nasa/osal#449 this changes the name from mcp750-vxworks to generic-vxworks, and from pc-linux to generic-linux, respectively.

**Describe the solution you'd like**
Change the PSP references to match the OSAL BSP name.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
The change in nasa/osal#449 makes the BSP modules more generic and changes the name.  This changes the PSP reference to be compatible.

**Testing performed**
Build for all platforms and sanity check CFE operation

**Expected behavior changes**
No change to behavior.

**System(s) tested on**
Ubuntu 20.04 (native)
RTEMS 4.11 on pc686 / QEMU
VxWorks 6.9 on MCP750

**Additional context**
Makes build compatible with nasa/osal#449

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
Note, initially created as draft due to baseline differences.  Other code needs to be merged first and then this will need to be rebased.

**Comment by astrogeco** [comment]
CCB 20200520 -  APPROVED

**Comment by astrogeco** [comment]
@jphickey should I remove the draft status from this and merge?

**Comment by jphickey** [comment]
> @jphickey should I remove the draft status from this and merge?

Hold off on this one until next cycle - will rebase....
But the PR #163 should be merged if possible (its a dependency)

**Comment by jphickey** [comment]
Rebased, should be good to go now.

**Comment by skliper** [comment]
@astrogeco This is the PSP side for the OSAL change... project priority.

**Pull request merged**
