### PR TITLE
Fix #359, Remove 'return;' from last line of void function.

### LINKED ISSUE #359: Remove "return;" from last line of void functions
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
"return;" at last line in void function is redundant.
Copy of https://github.com/nasa/cFE/issues/1540

**Describe the solution you'd like**
Remove

**Reporter Info**
@thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Fixes #359
Removes a single (the only) case of redundant "return;" statement on the last line of a void function.
Corrected a typo in the comments that was noticed along the way.

**Testing performed**
None, prior to submission.

**Expected behavior changes**
No impact on behavior.

**Contributor Info**
@thnkslprpt

### CODE REVIEW

**Comment by ArielSAdamsNASA** [comment]
@thnkslprpt Can you take a look at the format check workflow and fix the issue caught by it? Specifically about `void CFE_PSP_SetDefaultExceptionEnvironment(void)`. Thank you!

**Comment by thnkslprpt** [comment]
> @thnkslprpt Can you take a look at the format check workflow and fix the issue caught by it? Specifically about `void CFE_PSP_SetDefaultExceptionEnvironment(void)`. Thank you!

It seems that the warning was deemed ignorable in this case, given that the pull request was merged, which is good because I was having trouble deciphering exactly what the error was referring to anyway. Was it just due to the empty function?

**Comment by chillfig** [comment]
> > @thnkslprpt Can you take a look at the format check workflow and fix the issue caught by it? Specifically about `void CFE_PSP_SetDefaultExceptionEnvironment(void)`. Thank you!
> 
> It seems that the warning was deemed ignorable in this case, given that the pull request was merged, which is good because I was having trouble deciphering exactly what the error was referring to anyway. Was it just due to the empty function?

The "error on differences" step of the format check workflow (https://github.com/nasa/PSP/actions/runs/3163591969/jobs/5151273223) looks something like this:

16 -void CFE_PSP_SetDefaultExceptionEnvironment(void)
17 -{
18 -}
19 +void CFE_PSP_SetDefaultExceptionEnvironment(void) {}

The check recommends removing lines 16-18 by "-" before the line. The check recommends adding line 19 by showing "+" before the line.

**Comment by thnkslprpt** [comment]
> The check recommends removing lines 16-18 by "-" before the line. The check recommends adding line 19 by showing "+" before the line.

Ah OK thanks Justin. Yes I get the format now.
Cheers

**Pull request merged**
