### PR TITLE
Fix #121, Unify CFE PSP with OSAL BSP

### LINKED ISSUE #121: Improve consistency and reduce duplication in PSP BSP implementation
**Is your feature request related to a problem? Please describe.**
See https://github.com/nasa/osal/issues/261, where this ticket is to address item 3 to reduce code duplication in the PSP's.

**Describe the solution you'd like**
The CFE PSP should be an extension of the OSAL BSP, not a replacement for it. The PSP already defines a CFE_PSP_Main() entry point for itself, and this can be invoked as a second-stage after OS_Application_Startup to do the additional startup tasks required for CFE.

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Instead of redefining the basic entry point symbols, use the OSAL BSP and its abstractions.  The CFE PSP just becomes an extension to the OSAL BSP, and only needs to define the OS_Application_Startup symbol like any other OSAL application.

Fixes #121 

**Testing performed**
Build code for all supported targets (ppc-vxworks6.9, i686-rtems4.11, native/x86-64 linux). Verify clean build. Confirm CFE boots and responds to commands as normal for RTEMS and native linux targets.

**Expected behavior changes**
No behavior changes.  Code structure/linking change only.

**System(s) tested on**
Ubuntu 18.04 LTS 64 bit (native, build host)
QEMU for RTEMS 4.11

**Additional context**
VxWorks testing pending on availability of test platform

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
Note - this pull request depends on the OSAL BSP changes associated with nasa/osal#261 in pull request nasa/osal#404.

It should be merged at the same cycle that pull request.

**Comment by astrogeco** [comment]
CCB 20200408 - APPROVED

**Comment by skliper** [comment]
I checked out nasa/osal#404 along with this branch and build failed for SIMULATION=native, ENABLE_UNIT_TESTS=true...

```
/export/home/jhageman/cFS/cFS-GitHub/psp/fsw/pc-linux/src/cfe_psp_memory.c: In function ‘CFE_PSP_InitProcessorReservedMemory’:
/export/home/jhageman/cFS/cFS-GitHub/psp/fsw/pc-linux/src/cfe_psp_memory.c:670:60: error: ‘S_IRWXU’ undeclared (first use in this function)
    tempFd = open(CFE_PSP_CDS_KEY_FILE, O_RDONLY | O_CREAT, S_IRWXU );
```

**Comment by skliper** [comment]
See also https://travis-ci.com/github/skliper/cFS/jobs/318899041, shows failure with the two branches.  Is there another pull that needs to be included? @jphickey

**Comment by jphickey** [comment]
Did you also include nasa/cfe#585?  This needs to be merged together with the others.

Looking at the CFE, I'm not seeing this merged into the integration-candidate yet.  Note that the CFE merge can happen before the OSAL/PSP ones (it will have no effect) but it cannot happen after.

**Comment by skliper** [comment]
> Did you also include [nasa/cFE#585](https://github.com/nasa/cFE/pull/585)? This needs to be merged together with the others.

That worked.  Would help to have the version information covering what was tested in the pull request, it's not clear what was tested here.

**Comment by skliper** [comment]
18/56 Test #18: coverage-shared-filesys ..........***Failed    0.01 sec

Using nasa/cFE#585, #149, nasa/osal#404 with the bundle

**Comment by skliper** [comment]
4 failures in the test... fixing them now.

**Comment by skliper** [comment]
Rebased on master so it can be tested with the bundle

**Pull request merged**
